language: node_js
node_js:
  - "8.11.2"
cache:
  directories:
    - node_modules

before_install: cd client

script:
  - npm run lint
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep-history: true
  local-dir: client/dist
  on:
    branch: master
